### ISSUE TITLE
New Binding Syntax

### ISSUE THREAD

**Issue by jacwright** [teamsnap/chip#24]
I'd like to propose new binding syntax that I feel clarifies the code and reduces ambiguity about how binding works. This is a fuller discussion about the #19 and #20.

Currently Chip always and only works with attributes prefixed with a dash (e.g. `bind-text="an expression"`). This works but there are 2 drawbacks:
  1. Data-bound expressions are hard to see/find in a block of HTML because they look *exactly* like every other attribute.
  2. Working with *only* attributes has some drawbacks with verbosity, requiring extra HTML tags for binding text when otherwise the elements wouldn't be included (e.g. `Hello <span data-text="user.name"></span>`).

In #19 it is proposed to identify attributes more uniquely using some sort of bracket like: `[text]=""`, `(click)=""`, or `{local-prop}=""`. This would help with item 1.

In #20 it is proposed to add curly brackets to process text and attributes like: `href="/images/{{user.avatar}}"` or `Hello {{user.name}}`. This is a nice add, but it then becomes confusing when to use the `{{ }}` syntax and when not to.

I propose that we modify the current binding so that `{{ }}` always indicates a JavaScript expression, and attributes without curly brackets are treated as plain strings (even when used with bound attributes). This will add a lot of curly brackets to existing code, but it gives us a few benefits.
  * It is consistent. Everywhere you see `{{ }}` you know it is an expression. Everywhere else, you know it is *not* an expression.
  * `bind-if="{{event.isGame}}"` is even easier to pick out and grock than `[if]="event.isGame"` (although I still like the `[if]` notation in addition).
  * Using `{{ }}` eliminates the need for single-ticks within attributes which are harder to read. Take these examples:
    * `<img bind-href="'/images/avatars/' + user.avatar">` vs <br>
      `<img bind-href="/images/avatars/{{user.avatar}}">`
    * `<div bind-partial="'events'">` vs <br>
      `<img bind-partial="events">` (non `{{ }}` are just strings)

Combining these two changes together we get more obvious HTML that is easier to scan and grock.
```html
<div [if]="{{event.isGame}}">
  <h3>{{event.name}} <img [if]="{{event.image}}" src="{{event.image}}" alt="{{event.name}}"></h3>
  <div class="details">...</div>
</div>
```

Questions:

  * **Is this code: palatable, easier to read, easier to code, more understandable?**
  * **Are there adjustments or alterations to this suggestion that might make it better in some way, and how does it make it better?**

**Comment by dmvt** [comment]
I like the idea of {{ expression / var }} in the html, but I'm not thrilled about moving away from data-attrs. In general, I'd like to stay close to the syntax of the other major frameworks. This will decrease friction should someone who is familiar with other frameworks.

I propose making the following things work

<div (data-)bind-_attr_="expression"></div>
<div (data-)bind-_attr_="{{ expression }}"></div>
<div>{{ expression }}</div>

This is also partly because I don't want to have to rewrite everything I've already written to upgrade chip.

**Comment by matthopson** [comment]
I've definitely wanted to bring in the use of `{{expression}}` brackets. I agree that there many times when we don't need extra span tags laying around or what have you. 

In terms of the attributes themselves. I'm not a fan of bracketing them.. mainly because that's just a lot of stinking brackets.

`<div [if]="{{isTrue}}"></div>` hurts my pinky :(

**Comment by jacwright** [comment]
We'll leave the attribute's names as-is and work towards making the binding consistent by always using `{{ }}` for expressions, including allowing them in regular attributes and within text.
